# Generated by Django 5.2.7 on 2025-11-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("username", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                (
                    "ci",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_course", models.CharField(max_length=20)),
                ("grade", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("username", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "ci",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("grade", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("username", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "ci",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("subject", models.CharField(max_length=40)),
                ("type", models.CharField(max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_students.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Punctuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_students.evaluation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_students.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="model_students.teacher",
                verbose_name="assigned teacher",
            ),
        ),
    ]
